POST http://localhost:5000/api/quizRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydnA4NUxrbmxPbFpzSEl2Z29NVE5FdGp1Q1AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDc1MjgxMDAsImZ2YSI6Wzc5LC0xXSwiaWF0IjoxNzQ3NTI4MDQwLCJpc3MiOiJodHRwczovL2xvZ2ljYWwtYnVsbGZyb2ctMzYuY2xlcmsuYWNjb3VudHMuZGV2IiwibmJmIjoxNzQ3NTI4MDMwLCJzaWQiOiJzZXNzXzJ4RkE3dVZndTU0Q1B3VWFjY0Rva2J6Ym5JciIsInN1YiI6InVzZXJfMnZ6d1QyajRKTUZDa21vTHgyMVBUa2ZxcWZFIiwidiI6Mn0.XRjQEvqSlQNl7jQhwfly_bebbd7cJ5Ycxd3v1j_GRzRMoZQjlAmqNRVQU3AKYjVjLU4t07L_33JvKZZKrQPtiGKTa_iF4wQl9C5hNyQawe9qfgzDhe1wjNdMjbHZBIBBFyv1B7JJ11ak-yMTH9VogDyjWBwXjpZ5QA7K1DqQXB8XkRrjnhXf1MzHoNTpRNPzX2H3BVktb0OVW_GbYVLXxFr0tJa_M_evmBHjkjhh5X9h3axFNDKuuJG0sidcvr-C2-jskkryhPk1ypNM6_FHhyxruR17EGOk8RF_vM5hjKBXRsTiiDt_-kNTMNmOhQXCUtTFo3OgN0KjLuBF5Uv3Mg

{
  "quizId": "681c5216c7444fa182aed926",
  "durationMinutes": 123,
  "startTime": "2025-05-18T16:39:00.000Z"
}

