POST http://localhost:5000/api/quizRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydnA4NUxrbmxPbFpzSEl2Z29NVE5FdGp1Q1AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDgzNTI1MTAsImZ2YSI6WzAsLTFdLCJpYXQiOjE3NDgzNTI0NTAsImlzcyI6Imh0dHBzOi8vbG9naWNhbC1idWxsZnJvZy0zNi5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDgzNTI0NDAsInNpZCI6InNlc3NfMnhnR2tnM1ZIOUpqcjFzMzdLWXVlU3V4V25oIiwic3ViIjoidXNlcl8yeEFlTmN6aHAzV1JDNTFsOTRrdGg5ZHJCM2UiLCJ2IjoyfQ.g5tmnTqbqXbyG6rg5eP6IaUZppn522xREgZcOZ2O8eZISZm-7Bdgojn-rwdg-SQoa1T0d8-fW7ErP8mRqe2f17oaLIq1YpVT-iBYmX--uCk83MtkFAiHTx0kRy6LeXgQo71ktEUvRDMxQHFwxwn4dJhDHAACm3B49nqnyczxoMhwfo8w4RT2MnRSTc5v3V8GZPEOJp1za_Ksku6izR_znd0IxhCMBIy4aIv20VI0NYO7JzhN0qQ9Btibb4y0MSKI89PdmmESHKcFvKD2eQYdK54PvDALDXrpVGer9gKo1QRdnXrr1kFZdCgKxPaslEC_H_EJL0FMm5_42qx2IkKXNw

{
  "quizId": "681c5216c7444fa182aed926",
  "examSetId": "681c5216c7444fa182aed926",
  "durationMinutes": 123,
  "startTime": "2025-05-18T16:39:00.000Z"
}

