POST http://localhost:5000/api/quizRoom
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJSUzI1NiIsImNhdCI6ImNsX0I3ZDRQRDExMUFBQSIsImtpZCI6Imluc18ydnA4NUxrbmxPbFpzSEl2Z29NVE5FdGp1Q1AiLCJ0eXAiOiJKV1QifQ.eyJhenAiOiJodHRwOi8vbG9jYWxob3N0OjUxNzMiLCJleHAiOjE3NDc5MTEwODAsImZ2YSI6WzY0NjIsLTFdLCJpYXQiOjE3NDc5MTEwMjAsImlzcyI6Imh0dHBzOi8vbG9naWNhbC1idWxsZnJvZy0zNi5jbGVyay5hY2NvdW50cy5kZXYiLCJuYmYiOjE3NDc5MTEwMTAsInNpZCI6InNlc3NfMnhGQTd1Vmd1NTRDUHdVYWNjRG9rYnpibklyIiwic3ViIjoidXNlcl8ydnp3VDJqNEpNRkNrbW9MeDIxUFRrZnFxZkUiLCJ2IjoyfQ.tBHSGe7OeJdXd-8u4NuwaWbVdYBTacbH5p_oDwqDXlpUXz2VlqqHM8ALghhWmPYUKipMcc7EbLeWPJBlj32HLIvXtRPClSnte0uXjzL2lsmfB61QNo5fQxsFohJmw-qUJZFVihdtHvirhQGkOKTw7OBu2UtwOOZGi9VVj8dDwkEBuNKo-7SOjpJOQiYfgHdN2B-_g_kcdP8yU6mNlVqtViipLgL52pYQGWRmqbyJ3yK2FrfMKIY7kKzZ2SIHrdSuX6QhIawtIgIN0Jrd3lJI9KTtBmK4JEVEpaBdUiy0H2Xy2THSmEE9RW_mzZTNVO-S__aW0LhgyWGQsq8rilxbyA

{
  "quizId": "681c5216c7444fa182aed926",
  "examSetId": "681c5216c7444fa182aed926",
  "durationMinutes": 123,
  "startTime": "2025-05-18T16:39:00.000Z"
}

